"""added mob in owner table

Revision ID: ae9e66831d88
Revises: 38db32dd7282
Create Date: 2022-02-26 15:21:10.735509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9e66831d88'
down_revision = '38db32dd7282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('mob', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'mob')
    # ### end Alembic commands ###
