"""empty message

Revision ID: 399dd7f6beec
Revises: 350daea75b5f
Create Date: 2022-03-06 20:37:12.799259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399dd7f6beec'
down_revision = '350daea75b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    # ### end Alembic commands ###
